### ISSUE TITLE
Запуск

### ISSUE THREAD

**Issue by Pererozhdennyy** [Electrominch/UPX-Crack#2]
Интересно запустить, но там ошибочка на ip, который недействительный

**Comment by Electrominch** [comment]
нужно заменить ссылку на UP-X, актуальная чтобы была. Они меняют их каждую неделю. Кстати проект не работает)

**Comment by Electrominch** [comment]
К сожалению не получится, она и не работала никогда))
ПРавда иногда в течение нескольких часов был винрейт 80%, но на долгий срок так и не заработало
